### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by xxlabaza** [DmytroVasin/bomber#1]
subj

![screen shot 2018-09-21 at 11 04 53](https://user-images.githubusercontent.com/584375/45868421-4bd42480-bd8e-11e8-9993-af70454ed5d5.png)

**Comment by DmytroVasin** [comment]
Fixed: Restarted Heroku dino.

![screen shot 2018-09-21 at 11 12 41 am](https://user-images.githubusercontent.com/1914001/45868859-7ecae800-bd8f-11e8-8eca-d66ac89fc9d1.png)

Thanks.
